import { Julius_Sans_One, Ubuntu } from "next/font/google";
import React, { ReactNode } from "react";
import "./globals.css";
import Header from "./Header/page";
import { Metadata } from "next";
import Footer from "./Footer/page";
import { Toaster } from "@/components/ui/sonner"

interface RootLayoutProps {
  children: ReactNode;
}

const julius = Julius_Sans_One({
  subsets: ["latin"],
  variable: "--font-julius-sans-one",
  display: "swap",
  weight: "400",
});
const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--font-ubuntu",
  display: "swap",
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Exceleed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${julius.variable} ${ubuntu.variable}`}>
      <body>
        <header className="fixed top-0 z-10 w-full md:px-20 backdrop-blur-lg">
          <Header />
        </header>
      
        <main className="flex-1">
          <div className="2xl:min-w-full mr-auto ml-auto mb-0 sticky">{children}</div></main>
          <Toaster />
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}


